version: 2.1

jobs:
  test:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  test:
    jobs:
      - test
